/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Setting = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const Variant = IDL.Record({
  'name' : IDL.Text,
  'shippingCountries' : IDL.Vec(IDL.Text),
  'specs' : IDL.Vec(Setting),
  'currency' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'apps' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'variants' : IDL.Vec(Variant),
  'version' : IDL.Text,
  'specs' : IDL.Vec(Setting),
  'notes' : IDL.Vec(IDL.Text),
  'colors' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Setting = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const Variant = IDL.Record({
    'name' : IDL.Text,
    'shippingCountries' : IDL.Vec(IDL.Text),
    'specs' : IDL.Vec(Setting),
    'currency' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'apps' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'variants' : IDL.Vec(Variant),
    'version' : IDL.Text,
    'specs' : IDL.Vec(Setting),
    'notes' : IDL.Vec(IDL.Text),
    'colors' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };